Use existing dependencies for other configurations
SpineEventEngine/mc-java pull request #112
Opened 2023-09-03 23:09 UTC by alexander-yevsyukov

This PR teaches McJava to use existing dependencies for other configurations. Previously, the dependencies were added using versions from the resources. Sometimes it is not convenient, especially when breaking API changes are introduced.

2023-09-03 23:16 UTC, alexander-yevsyukov commented
The build depends on [this PR in `tool-base`](https://github.com/SpineEventEngine/tool-base/pull/60).

2023-09-04 08:44 UTC, dmdashenkov approved these changes
LGTM once the checks pass.

2023-09-04 08:55 UTC, armiol requested changes
@alexander-yevsyukov let's discuss this idea vocally first.

2023-09-19 19:08 UTC, alexander-yevsyukov commented
As agreed with @armiol vocally, we're going to keep this PR for a while in case we'd want this additional flexibility. For now the conclusion is that we prefer a fixed version stored in resources.

2023-10-11 16:47 UTC, merged