Migrate entity-related codegen to ProtoData
SpineEventEngine/mc-java pull request #132
Opened 2024-02-07 15:28 UTC by alexander-yevsyukov

2024-03-23 03:32 UTC, alexander-yevsyukov commented
@armiol, just FYI. It finally builds again. 

“Getting better, every day...” :)

2024-04-02 10:37 UTC, armiol requested changes
@alexander-yevsyukov please see my comments.

Other that that, great PR.

2024-04-02 10:37 UTC, armiol commented on buildSrc/src/main/kotlin/module.gradle.kts
> +                    "org.yaml:snakeyaml:2.1",
Please extract to the corresponding dependency object.

2024-04-02 10:37 UTC, armiol commented on mc-java-base/src/main/proto/spine/tools/mc/java/config.proto
> +    //  3. events — in files ending with "events.proto", and
This should go under 2. 
And the next one should go under 3.

Or please explain the idea.

2024-04-02 10:37 UTC, armiol commented on mc-java-entity/src/main/kotlin/io/spine/tools/mc/entity/EntityDiscoveryProcess.kt
> + * Gathers entity states declared in proto files.
Ideally, the process should just transform the events by filtering out those not matching our Entity conventions. But not gather. Gathering is a responsibility of some projection, which in this case would be subscribed to `EntityStateDiscovered`.

Let's discuss.

2024-04-02 10:37 UTC, armiol commented on mc-java-entity/src/main/kotlin/io/spine/tools/mc/java/entity/EntityStateRenderer.kt
> +    abstract fun doRender(type: MessageType, sources: SourceFileSet)
Please document.

2024-04-02 10:37 UTC, armiol commented on mc-java-entity/src/main/kotlin/io/spine/tools/mc/java/entity/column/ColumnAccessor.kt
> +internal class ColumnAccessor(
I would name it `ColumnAccessorMethod`. Or `ColumnAccessorGen`.

Right now, located next to `ColumnRenderer`, it looks as something that reads column values. While it does not do that, it just generated a code which does.

2024-04-02 10:37 UTC, armiol commented on mc-java-entity/src/main/kotlin/io/spine/tools/mc/java/entity/column/ColumnClassFactory.kt
> + * Creates a class called `Column` and nest it under the top level entity state class.
"nests".

2024-04-02 10:37 UTC, armiol commented on mc-java-protoc/src/main/java/io/spine/tools/mc/java/protoc/Plugin.java
> +                //ColumnGen.instance(config),
Not sure why this is commented out. Let's discuss.

2024-04-02 17:20 UTC, armiol approved these changes

2024-04-02 17:50 UTC, merged