Migrate query generation to ProtoData plugin
SpineEventEngine/mc-java pull request #141
Opened 2024-05-29 18:21 UTC by alexander-yevsyukov

This PR migrates generation of `Query` and `QueryBuilder` classes for entity states to be parts of `EntityPlugin`, which is a ProtoData plugin. Previously, code generation for queries and their builders was implemented as a part of McJava `protoc` plugin.

New code generation uses simple class references for the types in the same package with the current entity state class.
Compare:

**Previous version**
```java
  @javax.annotation.Generated("by Spine Model Compiler")
  public static final class QueryBuilder extends io.spine.query.EntityQueryBuilder<io.spine.tools.column.ProjectId, io.spine.tools.column.Project, QueryBuilder, Query> {
```

**After this PR**
```java
    @javax.annotation.Generated("by Spine Model Compiler (version: 2.0.0-SNAPSHOT.208)")
    public static final class QueryBuilder extends io.spine.query.EntityQueryBuilder<ProjectId, Project, QueryBuilder, Query> {
```

## Changes in details
 * `QuerySupportRenderer` class was added to `EntityPlugin`. The class is responsible for generating classes `QueryBuilder` and `QueryBuilder`. The class also renders the `query()` method, which returns `QueryBuilder`.
 * `mc-java-entity-tests` module was introduced covering code previously tested only in integration tests. Generation of `Query` and `QueryBuilder` classes is now also functionally-tested in this module.
 * `PluginTestSetup` test fixture was introduced in `mc-java-base` module.

## Other notable changes
 * `FieldClassFactory` was renamed to `FieldClass`.
 * `ColumnClassFactory` was renamed to `ColumnClass`.
 * `VersionHolder` utility object was introduced for lazily loading the version of McJava from the JAR manifest.
 * `GeneratedAnnotation` utility object was introduced.
 * Constants for names of generated classes were moved to `EntityPlugin` because we need them in the functional tests in the `mc-java-entity-tests` module.
 * The method `runPipelineWithDefaultSettings()` was renamed to `runWithDefaultSettings()`.

2024-05-31 18:42 UTC, armiol requested changes
Almost LGTM. Please see my comment.

2024-05-31 18:42 UTC, armiol commented on mc-java-entity-tests/build.gradle.kts
> +//        gradleTestKit(),
Please review this commented line and those below.

2024-05-31 19:54 UTC, alexander-yevsyukov commented on mc-java-entity-tests/build.gradle.kts
> +//        gradleTestKit(),
Sorry, I have requested review on this PR by mistake: I confused it with the PR in ProtoData because they were in the adjacent tabs... :)

I've turned it back to draft and going to return to it after updates to `base`, ProtoData, and ProtoTap related to loading `CodeGeneratorRequest` we discussed and worked on today.

2024-06-08 17:01 UTC, armiol approved these changes
@alexander-yevsyukov LGTM with a single comment.

2024-06-08 17:03 UTC, armiol commented
@alexander-yevsyukov I also have a question regarding the PR description.

Here is an excerpt:

----
**After this PR**
```java
    @javax.annotation.Generated("by Spine Model Compiler (version: 2.0.0-SNAPSHOT.208)")
    public static final class QueryBuilder extends io.spine.query.EntityQueryBuilder<ProjectId, Project, QueryBuilder, Query> {
```
----

Why `io.spine.query.EntityQueryBuilder` part is an FQN? Doesn't the PSI magic import it for us?

2024-06-08 17:34 UTC, alexander-yevsyukov commented
> Why `io.spine.query.EntityQueryBuilder` part is an FQN? Doesn't the PSI magic import it for us?

Unfortunately, it does not because our PSI setup does not include adding the whole classpath.

2024-06-08 18:03 UTC, merged