Handle `compary_by` option
SpineEventEngine/mc-java pull request #154
Opened 2024-08-27 15:34 UTC by yevhenii-nadtochii

2024-08-27 16:18 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/AddCompareToMethod.kt
> + * @property type the type of the message.
These things are `@param`s.

2024-09-06 20:06 UTC, yevhenii-nadtochii commented
@alexander-yevsyukov @armiol PTAL

2024-09-08 20:58 UTC, alexander-yevsyukov commented
@yevhenii-nadtochii, let's discuss the Concerns section on a video call on Monday.

2024-09-08 22:09 UTC, alexander-yevsyukov requested changes
Please see my comments.

2024-09-08 22:09 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/WellKnown.kt
> +    private val values = listOf(
Why do we want this split?

Why cannot we have a map for all known messages disregarding their internals?

2024-09-08 22:09 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/WellKnown.kt
> +internal object WellKnown {
Why do we want to hide this under `io.spine.tools.mc.java.comparable.action` package?

2024-09-08 22:09 UTC, alexander-yevsyukov commented on tests/mc-java-comparable/src/test/java/io/spine/tools/mc/java/comparable/ComparablePluginTest.java
> + * http://www.apache.org/licenses/LICENSE-2.0
Please use `https://`

2024-09-08 22:09 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/WellKnown.kt
> +internal object WellKnown {
We need to have an ability to supply a default `Comparator` for already existing code (e.g. `LatLng`) and then make the code generation (and generated code) use the registered `Comparator` for that type.

2024-09-08 22:09 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/WellKnown.kt
> +internal object WellKnown {
It should work similarly to extensions for options, when we update a type registry using the services mechanism.

2024-09-09 14:37 UTC, yevhenii-nadtochii commented on mc-java-comparable-tests/src/test/kotlin/io/spine/tools/mc/java/comparable/AddComparatorSpec.kt
> +                    "java.util.Comparator.comparing(($message $instance) -> $instance.getResidence().getRegion())" +
Issue on this: https://github.com/SpineEventEngine/mc-java/issues/157

2024-09-09 15:54 UTC, yevhenii-nadtochii commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/CompareByOption.kt
> +internal fun isComparable(option: Option): Boolean = option.name == COMPARE_BY_OPTION_NAME
It is not an extension because I use it only with collections: `any(::isCompareBy)` or `find(::isCompareBy)`.

2024-09-11 17:28 UTC, yevhenii-nadtochii commented
Converting it back to draft because it was temporarily postponed.

The current state of affairs:

1. Most comments above have been addressed, except for two comments about TODOs that should be discussed.
2. `ComporatorRegistry` has been integrated "as is", without refactoring. Though, it works fine. I've added one more integrated test to cover usage of the registry in runtime.
3. `Concerns` section remains valid for discussion.

2024-09-16 08:20 UTC, armiol commented
@yevhenii-nadtochii I have removed myself from the reviewers, so that this PR don't come up in my "to review" list until it is a draft.

Feel free to put me back to the reviewers once the PR is ready.

2024-10-10 15:29 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov PTAL

2024-10-10 16:01 UTC, alexander-yevsyukov requested changes
Please see my comments.

2024-10-10 16:04 UTC, alexander-yevsyukov commented
@yevhenii-nadtochii, please apply [latest ProtoData](https://github.com/SpineEventEngine/ProtoData/pull/271). It brings newer `core-java` which deprecates our `Nothing` type and related calls.

2024-10-10 16:15 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/ComparatorBuilder.kt
> + * Please note the line breaks were added manually for reader's convenience. The builder
Please have a line break here before `The builder`. For the reader's convenience. Also a new line before the next sentence would make it a bit easier to read.

2024-10-10 16:19 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/ComparisonField.kt
> +            "The repeated fields can't participate in comparison: `$field`."
Maps cannot participate either. Please adjust the message to be more precise about the conditions.

2024-10-10 16:21 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/FieldPath.kt
> +internal typealias FieldPath = String
We have `io.spine.base.FieldPath` type. It is not a big deal, but please consider renaming this type alias to `FieldReference` to avoid the confusion with the type from `base`.

2024-10-10 16:23 UTC, armiol requested changes
@yevhenii-nadtochii 32/60 reviewed.

2024-10-10 16:23 UTC, armiol commented on mc-java-comparable-tests/src/testFixtures/proto/given/comparable/account.proto
> +    UNDEFINED = 0;
Technically, it should be `AS_UNDEFINED`.

2024-10-10 16:23 UTC, armiol commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/FieldLookup.kt
> +package io.spine.tools.mc.java.comparable.action
This type (and its siblings, such as `FieldPath`) look as a part of a more generic utility. We may need the same lookup in other cases as well (`(max).value = "another_field.value"`).

Consider moving them to a more appropriate module and package.

@alexander-yevsyukov FYI.

2024-10-10 16:23 UTC, armiol commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/FieldPath.kt
> +internal typealias FieldPath = String
Just in case, we [already have](https://github.com/SpineEventEngine/base/blob/b7be0e99de848f7048ec03f4f877d966eff88da1/src/main/proto/spine/base/field_path.proto#L55) the same term.

P.S. GitHub search (inside of our organization, of course) rulezzz.

2024-10-10 16:24 UTC, alexander-yevsyukov commented on tests/mc-java-comparable/src/test/java/io/spine/tools/mc/java/comparable/ComparablePluginTest.java
> +        assertEquals(expected, localDateTimes);
Please use assertions from Truth.

2024-10-10 16:33 UTC, alexander-yevsyukov commented
@yevhenii-nadtochii, 
> `AddComparator`: this is the smartest action. It performs analysis of Proto messages, indeed. I'm not sure if it should be done in an entity of `DirectMessageAction` type.

The class is complex enough, but not too much. It looks like the best place to perform this analysis. The improvements I can suggest is to make diagnostic messages a bit more helpful for the user. Please see my latest comments on this.

2024-10-10 17:10 UTC, armiol requested changes
@yevhenii-nadtochii 60/60 reviewed. Please see my comments.

2024-10-10 17:10 UTC, armiol commented on tests/mc-java-comparable/build.gradle.kts
> +    named<JavaExec>("launchTestProtoData") {
Let's use [this](https://github.com/SpineEventEngine/mc-java/blob/master/buildSrc/src/main/kotlin/BuildExtensions.kt#L234) instead.

As far as I recall, the `tests/buildSrc` folder is a symlink for `<root>/buildSrc`.

2024-10-10 17:10 UTC, armiol commented on tests/mc-java-comparable/src/test/java/io/spine/tools/mc/java/comparable/env/Students.java
> +    public static List<Student> notSorted() {
"unsorted"?

2024-10-10 17:10 UTC, armiol commented on tests/mc-java-comparable/src/test/java/io/spine/tools/mc/java/comparable/package-info.java
> +package io.spine.tools.mc.java.comparable;
This is weird. We have this very package in the module-under-test. I suspect it is a target for the code-generated types, but still, it would be better to name it differently.

The reason is a potential split-package issue, that we will occur once we attempt to enable the Java module mode.

2024-10-10 17:10 UTC, armiol commented on tests/mc-java-comparable/src/test/proto/given/comparable/student.proto
> +// Comparable by `int` and `string` fields, has the reversed ordering.
"reverse".

2024-10-11 16:40 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov PTAL

2024-10-11 17:05 UTC, armiol requested changes
@yevhenii-nadtochii still in review, but please see my comment already.

2024-10-11 17:05 UTC, armiol commented on mc-java-base/src/main/kotlin/io/spine/tools/mc/java/field/FieldPathExts.kt
> +package io.spine.tools.mc.java.field
`io.spine.tools.mc.java.field` is about Java fields which reflect those declared in Proto (see the corresponding `package-info.java`). While `FieldPath` is purely about Proto declarations.

Here, in the office, we have just discussed the potential package for these extensions, and came up with `io.spine.tools.mc.java.base`, which would in a way rhyme with `... base` package being a motherland for `FieldPath` type.

2024-10-11 17:19 UTC, armiol requested changes
@yevhenii-nadtochii see more comments.

2024-10-11 17:19 UTC, armiol commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> + * Builds and inserts a static `comparator` field into the message that qualify as comparable.
Maybe, "...the messages that qualify..."?

Or, "...the message that qualifies..."?

2024-10-11 17:19 UTC, armiol commented on mc-java-base/src/main/kotlin/io/spine/tools/mc/java/message/MessageLookup.kt
> +public class MessageLookup(private val context: CodegenContext) {
This comment relates not only to this `MessageLookup` but to its `Lookup` siblings as well.

On the first (and all subsequent) sights, these three types are stateless (except for the `CodegenContext`, which is just technically a part of their state), and are rather methods or extensions (say, to `CodegenContext`), than standalone types. 

Another thing is that now that we have checked out the codebase and built it locally, we were able to graps the whole idea. Now, the suggestion is to get rid of querying the `CodegenContext` altogether, but rather use [ProtoData's `TypeSystem`](https://github.com/SpineEventEngine/ProtoData/blob/493466105ea704fbd9a7983124aad54d18615f0a/api/src/main/kotlin/io/spine/protodata/type/TypeSystem.kt).

It sounds like a bit of a hack, going around the presumably meaningful interaction with the read-side of the respective context. However, what we really need here is just filter the type definitions known to us at this point, and grab some of their properties. And `TypeSystem` seems to be the right and the most direct way to go.

Please have a look at the `TypeSystem`'s API, and see if we could get rid of these `Lookup` types.

We'll probably need to discuss this idea vocally, once you get the first impression of this suggestion.

2024-10-11 17:22 UTC, alexander-yevsyukov requested changes
Please see my comments.

2024-10-11 17:22 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/CompareByOption.kt
> +private const val COMPARE_BY_OPTION_NAME = "compare_by"
Can we get this name from corresponding descriptor?

2024-10-11 17:22 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/CompareByOption.kt
> +internal val MessageType.hasCompareByOption: Boolean
Why do we need this, having `io.spine.protodata.ast.find()` extension? Please see `OptionExts.kt` in ProtoData.

2024-10-11 17:22 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/ComparisonField.kt
> +                    "Please check the field type of `$field`."
We can detect the type of the field at this place and save the user some time. We need to be more specific about the current error and encourage the user to use another field or change its type.

2024-10-11 17:22 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/proto/spine/tools/mc/java/comparable/events.proto
> +    protodata.Actions actions = 3;
We should load these from settings instead of passing them in events. It's not a part of an event. The event tells about the fact.  Actions are the matter of the rendering components that act in response to gathered views.

Please see how other plugins do it.

2024-10-11 17:22 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/proto/spine/tools/mc/java/comparable/views.proto
> +    protodata.Actions actions = 3;
Actions are loaded from settings by rendering components. They do not belong to the view.

2024-10-15 09:20 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov PTAL

Also, I suggest overriding `RenderAction.context` and `RenderAction.typeSystem`, so that they are non-nullable for actions. Mark them as open in `Member`, and override in `RenderAction`. The action calls `registerWith(context)` in its `init` block.

2024-10-15 10:05 UTC, armiol requested changes
@yevhenii-nadtochii please see my comments so far. I will continue the review in IDE, as it's difficult to follow via GitHub.

2024-10-15 10:19 UTC, alexander-yevsyukov commented on mc-java-base/src/main/kotlin/io/spine/tools/mc/java/base/FieldPathExts.kt
> +public fun TypeSystem.resolve(fieldPath: FieldPath, message: MessageType): Field {
@armiol, I have similar logic in ProtoData. Have a look at [ensureField()](https://github.com/SpineEventEngine/ProtoData/pull/272/files#diff-588bb41b2d45c1fd76c138ea85a3c9f3e29d4e2c154fea3673b465f1b6008022) in `Options.kt`.

I think this extension (with tests) should belong to ProtoData. Plus, extensions to `FieldPath` should belong to `base`, where the type is declared.

So, I suggest the following plan:
 1. I pick up extensions to `FieldPath` and add them to `base`.
 2. I pick up the `TypeSystem` extension, cover it with tests in ProtoData, and use it instead of my current code in PR.
 3. Yevhenii finish this PR sooner, and switches to other tasks.
 4. Yevhenii or me migrate to new extensions in `base` and ProtoData during the next round of visiting McJava.

2024-10-15 10:33 UTC, yevhenii-nadtochii commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/ComparatorBuilder.kt
> + * The builder doesn't add them. It will be a single line of text.
I see in integration tests output that the comparator remains unformatted. 

This comment relates to this particular builder so that no one expected `build(): String` to return a string as from the KDoc snippet.

2024-10-15 10:48 UTC, alexander-yevsyukov requested changes
Please see my comments.

2024-10-15 10:48 UTC, alexander-yevsyukov commented on mc-java-base/src/main/kotlin/io/spine/tools/mc/java/base/FieldPathExts.kt
> +    val nextMessage = findMessage(currentField.type.message)!!.first
What if the referenced field is not of message type? I believe we need to tell about such an error.

2024-10-15 10:48 UTC, alexander-yevsyukov commented on mc-java-base/src/main/kotlin/io/spine/tools/mc/java/base/MessageTypeExts.kt
> +public fun MessageType.javaClass(accordingTo: ProtoFileHeader): Class<*>? {
This extension should go to ProtoData too.

2024-10-15 10:48 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                "The field `$path` has an unrecognized Proto field type: `$type`. " +
We need to standardize on capitalization of the word "proto". I think in the short form it should go in lowercase, while "Protobuf" is capitalized. This is the way Google use it in their sources, from what I remember.

2024-10-15 10:48 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                if (javaClass == null) {
What if we're rendering the code which is for the proto type in the same source set and has `compare_by` option?

In this case we don't have a `Class` yet, but we can calculate its name. I don't get why we need a real `Class` here. Please explain. Let's have a quick video call sometime later today. I would be more convenient, assuming the other comments and suggestions.

@armiol, FYI.

2024-10-15 10:48 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                "The field `$path` has an unrecognized Proto field type: `$type`. " +
Also, I'm not sure about "unrecognized". We do recognize the type because it's in the source code, descriptors, and is (at least) proto-compilable. Otherwise, we wouldn't have got this far.

But this type isn't probably "comparable" because it's a list, or a map.

2024-10-15 10:48 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                        "The supported Proto fields: primitives, enums and messages."
Suppose you're the person who gets this error message in console. What it would take to figure out the root cause of the error. Let's sum what we see in the diag message:

1. "Unrecognized type".
2. It's not "supported".
3. Supported types are primitives, enums, and messages. Please notice Oxford comma in the enumeration.
4. Stacktrace having "comparable".

In the end the combination above would give the reader idea that the field isn't probably comparable. 
But can we make this path to the conclusion a bit shorter?

2024-10-15 10:48 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +     * option in detail.
The reference to documentation details should probably be a part of the error diagnostics I mentioned above.

2024-10-15 10:48 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                    "The type of `${path.joined}` field must either have `compare_by` options OR " +
This message is good!

2024-10-15 10:48 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                val comparator = "io.spine.compare.ComparatorRegistry.get($className)"
Can we use the `reference` extension to the `ComparatorRegistry` class here? This way finding usages would pick up this dependency.

2024-10-15 10:48 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/ComparatorBuilder.kt
> + * For example, `my_best_field` will be converted to `getMyBestField`.
Why don't we use `FieldMethods` class here? This way we wouldn't have to explain the accessor convention in the docs.

2024-10-15 10:48 UTC, alexander-yevsyukov commented on tests/mc-java-comparable/src/test/java/io/spine/tools/mc/java/comparable/tests/env/LocalDateTimes.java
> + * Provides {@link LocalDateTime} instances for
Please mention that this `LocalDateTime` is a copy of the type provided by Spine Time library. 

It would same time for people familiar with the library (like me) in discovering that there are no imports for the type, and there's a `local_date_time.proto` file.

2024-10-15 11:36 UTC, yevhenii-nadtochii commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                "The field `$path` has an unrecognized Proto field type: `$type`. " +
This `unrecognized` is a stub error thrown when `ast.Type` has an unknown `kind`. It is not about a non-comparable type.

`kind` is represented by `oneof`, which has nothing to do with Kotlin's `when` (as for example, with `sealed` classes):

```
message Type {

    oneof kind {
        option (is_required) = true;

        TypeName message = 1;

        TypeName enumeration = 2;

        PrimitiveType primitive = 3;
    }
}
```

So, we have to provide `else` branch in case some new `kind` appears.

2024-10-15 11:45 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                "The field `$path` has an unrecognized Proto field type: `$type`. " +
OK. I get it. The problem it is buried inside extensions, and is not obvious from the branching here. Hence, my comment.

2024-10-15 12:53 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                if (javaClass == null) {
Discussed vocally: it's the case on external comparator only.

2024-10-15 13:02 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                        "The supported Proto fields: primitives, enums and messages."
Discussed the improved wording for the error message:

```
The field `$path` declared in the message type `$messageType` is not of the supported type (`$fieldType`) for the comparison. Supported field types are: primitives, enums, and messages.
```

2024-10-15 13:22 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/ComparatorBuilder.kt
> + * For example, `my_best_field` will be converted to `getMyBestField`.
Agreed to leave it as is in this PR. We may return to this code when attempting to migrate using `Expression` instead of `String`.

2024-10-16 11:09 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov PTAL

I will try bringing typed expressions to `ComparatorBuilder` with a separate PR. `TypeSystem.resolve(path)` also would go there when it is published.

2024-10-16 11:13 UTC, alexander-yevsyukov commented on mc-java-base/src/main/kotlin/io/spine/tools/mc/java/base/FieldPathExts.kt
> +public fun TypeSystem.resolve(fieldPath: FieldPath, message: MessageType): Field {
Resolving this because it's already done in [base](https://github.com/SpineEventEngine/base/pull/831) and [soon to be complete in ProtoData](https://github.com/SpineEventEngine/ProtoData/pull/272).

2024-10-16 11:20 UTC, alexander-yevsyukov approved these changes
LGTM with a couple of comments regarding diag. messages to consider before merging.

2024-10-16 11:20 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                    "The type of `${path.joined}` field should have `compare_by` option itself " +
We usually put the option in round braces when mentioning in the docs or diagnostic messages. I don't know who started this, and we probably don't have it standardized in our guidelines. But `(compare_by)` looks more visible and is clearly different to a field.

Also, the definite article should be probably put before the name.

2024-10-16 11:20 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                    "The type of `${path.joined}` field must either have `compare_by` options OR " +
Please also consider my comment about braces around the option name here.

2024-10-16 11:20 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                "primitives, enums, and comparable messages. Checks out docs to `compare_by` " +
Please consider braces around the option name in this message.

2024-10-16 11:20 UTC, alexander-yevsyukov commented on mc-java-comparable/src/main/kotlin/io/spine/tools/mc/java/comparable/action/AddComparator.kt
> +                    "The type of `${path.joined}` field should have `compare_by` option itself " +
@armiol, for your attention.

2024-10-16 11:32 UTC, armiol approved these changes
@yevhenii-nadtochii LGTM. 

However, please see my comment. Maybe, that's something we need to discuss.

2024-10-16 11:32 UTC, armiol commented on mc-java-comparable-tests/src/test/kotlin/io/spine/tools/mc/java/comparable/AddComparatorSpec.kt
> +    `not generate comparator` {
What do we think of `oneof`?

It's now in a gray zone. I would either have tests explicitly covering our support or our refusal to support the comparison by `oneof` fields.

2024-10-16 12:30 UTC, yevhenii-nadtochii commented on mc-java-comparable-tests/src/test/kotlin/io/spine/tools/mc/java/comparable/AddComparatorSpec.kt
> +    `not generate comparator` {
I've added the negative tests to cover `oneof`. Its support was not [declared](https://github.com/SpineEventEngine/base/blob/c0752da695acd1393c45508b2b491e938257f1b7/src/main/proto/spine/options.proto#L976).

2024-10-16 13:03 UTC, merged