Update to the latest `config`
SpineEventEngine/mc-java pull request #30
Opened 2022-04-06 13:26 UTC by yevhenii-nadtochii

2022-04-06 16:34 UTC, yevhenii-nadtochii commented on pom.xml
>    <dependency>
@sonatype-lift ignore

2022-04-06 16:34 UTC, yevhenii-nadtochii commented on pom.xml
>    <dependency>
@sonatype-lift ignore

2022-04-06 16:34 UTC, yevhenii-nadtochii commented on pom.xml
>    <dependency>
@sonatype-lift ignore

2022-04-06 16:34 UTC, yevhenii-nadtochii commented on pom.xml
>    <dependency>
@sonatype-lift ignore

2022-04-07 12:36 UTC, yevhenii-nadtochii commented
@armiol Please take a look.

2022-04-07 13:01 UTC, armiol requested changes
As discussed, please ensure that deleting the empty build files is absolutely safe, in terms of using `tests` root project in IDEA and in standalone builds. 

Also, please see my comment.

2022-04-07 14:11 UTC, merged