Apply `testFixtures` to the `mc-java-annotation` module
SpineEventEngine/mc-java pull request #70
Opened 2022-11-05 20:05 UTC by alexander-yevsyukov

This PR improves testing environment of the `mc-java-annotation` by applying `testFixtures` and [latest `tool-base`](https://github.com/SpineEventEngine/tool-base/pull/34).

2022-11-06 06:11 UTC, armiol requested changes
Please see my comments.

2022-11-06 06:11 UTC, armiol commented on mc-java-annotation/src/main/java/io/spine/tools/mc/java/annotation/mark/ModuleAnnotator.java
> +        public @Nullable Set<@Regex String> getInternalPatterns() {
This method should not return `null`, because

a) we initialize the patterns with some value upon creating the instance;

b) whoever sets any value to this set directly (now or in the future), should never be able to pass `null`, as usually we check every incoming bit in our public setters for that.

2022-11-06 06:11 UTC, armiol commented on mc-java-annotation/src/main/java/io/spine/tools/mc/java/annotation/mark/ModuleAnnotator.java
> +            return internalMethodNames;
Same as above.

2022-11-06 06:11 UTC, armiol commented on mc-java-annotation/src/test/kotlin/io/spine/tools/mc/java/annotation/gradle/AnnotatorPluginSpec.kt
> + * Compose the path to the main descriptor set file using the project Maven coordinates
"Composes"

2022-11-06 06:11 UTC, armiol commented on mc-java-annotation/src/testFixtures/java/io/spine/tools/mc/java/annotation/check/NestedTypesAnnotationCheck.java
> +                                      String.format("`%s` is not annotated.", nestedType.getQualifiedName()));
Can we use a static import, still? Or does it conflict with something?

2022-11-06 06:12 UTC, alexander-yevsyukov commented on mc-java-annotation/src/main/java/io/spine/tools/mc/java/annotation/mark/ModuleAnnotator.java
> +        public @Nullable Set<@Regex String> getInternalPatterns() {
What if we call if before anything was set?

2022-11-06 09:02 UTC, armiol commented on mc-java-annotation/src/main/java/io/spine/tools/mc/java/annotation/mark/ModuleAnnotator.java
> +        public @Nullable Set<@Regex String> getInternalPatterns() {
@alexander-yevsyukov 
Please see line 89.

Or I don't see something :(

2022-11-15 19:25 UTC, alexander-yevsyukov commented on mc-java-annotation/src/main/java/io/spine/tools/mc/java/annotation/mark/ModuleAnnotator.java
> +        public @Nullable Set<@Regex String> getInternalPatterns() {
You're right. Fixed.

2022-11-16 04:22 UTC, armiol approved these changes
LGTM with some minor comments.

2022-11-16 04:22 UTC, armiol commented on mc-java-annotation/src/main/java/io/spine/tools/mc/java/annotation/mark/ModuleAnnotator.java
> +        public @Nullable AnnotatorFactory getAnnotatorFactory() {
Please document the public API methods.

2022-11-16 11:46 UTC, merged